### ISSUE TITLE
Update collection summaries dashboard method

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/ghgc-backend#28]
# PI Objective
[A VEDA Data Services production stage is live#285](https://github.com/NASA-IMPACT/veda-architecture/issues/285)
[Objective 8: Official 1st release/launch of the GHG website #15](https://github.com/US-GHG-Center/ghgc-arch/issues/15)

# Description
Currently, the `dashboard.update_collection_default_summaries` method creates "summaries" for a collection which includes the datetime summary and `min` and `max` for the `cog_default` asset. Since we're supporting multiple assets now, this method has to be updated to create the `min` and `max` summary for all the item assets that exist in the collection.

**Comment by anayeaye** [comment]
This PR corrects the utility functions in postgres, we've already deployed and tested in VEDA: https://github.com/US-GHG-Center/ghgc-backend/pull/30.

I also have a one line change for the ghgc-stac-ingestor but am not able to contribute to that repo yet. @slesaad can you add me?

**Comment by slesaad** [comment]
@anayeaye thanks! i've added the permissions!
