### ISSUE TITLE
Deploy rio-tiler 6.5.0

### ISSUE THREAD

**Issue by j08lue** [US-GHG-Center/ghgc-backend#72]
rio-tiler [6.5.0](https://github.com/cogeotiff/rio-tiler/releases/tag/6.5.0) should fix the issue that was introduced after 6.2.3.post1 and present until 6.4.7.

We need rio-tiler >= 6.4.4 to have accurate zonal statistics, so [6.5.0](https://github.com/cogeotiff/rio-tiler/releases/tag/6.5.0) is the version we should deploy.

## Acceptance criteria

- [x] Deployed rio-tiler 6.5.0 to `dev`
- [x] Tested that there are no issues with tiles and statistics
- [x] https://github.com/US-GHG-Center/ghgc-backend/pull/74
- [x] Tested in `staging`
- [x] Deployed to `production`
- [x] Tested in `production`

**Comment by amarouane-ABDELHAK** [comment]
A PR was submitted to deploy the new rio-tiler version https://github.com/US-GHG-Center/ghgc-backend/pull/73 to dev

**Comment by j08lue** [comment]
## Tiling

Testing against https://dev.ghg.center/ghgcenter/api/raster, where 6.5.0 is deployed.

The pixel shifting issue (https://github.com/US-GHG-Center/ghgc-architecture/issues/212) is absent.

https://deploy-preview-349--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22micasa-co2-flux-npp-m%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22total-ch4%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2016-11-30T23%3A00%3A00.000Z&search=4dv

There are still some jumps in resolution, I assume as we switch between overviews, for example between zoom level 3 and 4, but that is as expected, currently

![image](https://github.com/US-GHG-Center/ghgc-architecture/assets/3404817/70f747f0-15df-43c7-8d43-2d3c7f78a96a)
![image](https://github.com/US-GHG-Center/ghgc-architecture/assets/3404817/23743ed3-debb-4e3d-9985-64ecdafb7829)

## Zonal statistics

Applying an intermediate equal-area projection gives more accurate results for `npp` assets from the `casagfed-carbonflux-monthgrid-v3` collection than using the native (WGS84) CRS, agreeing well with the benchmark:

![image](https://github.com/US-GHG-Center/ghgc-backend/assets/3404817/d17d4c15-06e2-4625-9928-dbf7e7bcd640)

Confirming that intermediate reprojection works as expected.

**Comment by j08lue** [comment]
So I can confirm that 6.5.0 has the accurate statistics from 6.4.7 that we approved and at least as accurate and sharp tiles as 6.2.3.post1.

So this is good to deploy.

**Comment by j08lue** [comment]
I see deployment to `production` is complete, so I visually inspected tile quality on https://staging.earth.gov/ghgcenter

https://deploy-preview-349--ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22total-ch4%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22micasa-co2-flux-npp-m%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2016-11-30T23%3A00%3A00.000Z&search=4dv&aois=%5B%5D&dateRange=

and also the zonal statistics from `https://ghg.center/api/raster` agree with our benchmark again

![image](https://github.com/US-GHG-Center/ghgc-backend/assets/3404817/26e24cb8-0413-42e2-bd2c-228133da8dac)

I also verified that zonal averages for a non-rectangular geometry agree between `dev` and `production`.

This verifies that the same performance we validated on `dev` is now available in `production`, so we are good to move forward.

It would be great to do further testing of the zonal statistics against other software and for various edge cases. We should follow up with that after the release. ([#FurtherResearchIsNeeded](https://en.wikipedia.org/wiki/Further_research_is_needed))
